--
-- Explain
--

-- pgsql> EXPLAIN (FORMAT JSON) select * from MYCHAT_USER;

--
-- Indexes
--

CREATE INDEX IDX_TBL_MYCHAT_USER_COL_IDENTIFICATION ON MYCHAT_USER USING BTREE(IDENTIFICATION);
CREATE INDEX IDX_TBL_MYCHAT_USER_COL_IDENTIFICATION ON MYCHAT_USER USING HASH(IDENTIFICATION);




